### ISSUE TITLE
[Issue] Issue with gpus on `alan-compute-07`

### ISSUE THREAD

**Issue by waliens** [montefiore-ai/alan-cluster#27]
**Describe the issue**
I have recently noticed a lot of failing jobs for an experiment I am currently running. I am 100% sure it doesn't come from my script because I have re-scheduled some of the failing jobs and most of them have completed successfully. I have tried several things (reducing batch size in case of OOM, double checking device allocation) before finding that all failing jobs have actually failed on node `alan-compute-07` while jobs running on other nodes have all completed successfully.

The jobs fail on this error:
```log
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[...]python3.6/site-packages/clustertools/environment.py", line 50, in __call__
    self.deserialize_and_run(serialized)
  File "[...]python3.6/site-packages/clustertools/environment.py", line 47, in deserialize_and_run
    lazy_computation()
  File "[...]python3.6/site-packages/clustertools/experiment.py", line 135, in __call__
    self.run(self.result, **actual_parameters)
  File "[...]eval_mh_features_svm_computation.py", line 110, in run
    score = eval_features(net, train_loader, eval_loader, scorer, device, n_jobs=self.n_jobs)
  File "[...]eval_mh_features_svm_computation.py", line 49, in eval_features
    x_train, y_train, groups_train = get_features(network, train_loader, device)
  File "[...]eval_mh_features_svm_computation.py", line 40, in get_features
    features.append(network(x).detach().cpu().numpy())
  File "[...]python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "[...]network.py", line 26, in forward
    return self.pool(self.features(x))
  File "[...]python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "[...]models.py", line 33, in forward
    x = self.layer1(x)
  File "[...]python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "[...]python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "[...]python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "[...]python3.6/site-packages/torchvision/models/resnet.py", line 83, in forward
    out = self.conv2(out)
  File "[...]python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "[...]python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
  
**Additional context**
```log
$ sacct -u rmormont --format="JobName%40,Nodelist,State,Elapsed,Start" -s F
[...]
Computati+ alan-compute-07     FAILED   00:01:53 2019-05-21T03:27:35
Computati+ alan-compute-07     FAILED   00:01:45 2019-05-21T03:28:49
Computati+ alan-compute-07     FAILED   00:01:58 2019-05-21T03:29:17
Computati+ alan-compute-07     FAILED   00:01:59 2019-05-21T03:29:28
Computati+ alan-compute-07     FAILED   00:02:03 2019-05-21T03:30:34
Computati+ alan-compute-07     FAILED   00:02:04 2019-05-21T03:31:15
Computati+ alan-compute-07     FAILED   00:02:04 2019-05-21T03:31:27
Computati+ alan-compute-07     FAILED   00:01:46 2019-05-21T03:32:37
Computati+ alan-compute-07     FAILED   00:01:47 2019-05-21T03:33:19
Computati+ alan-compute-07     FAILED   00:01:57 2019-05-21T03:33:31
Computati+ alan-compute-07     FAILED   00:01:53 2019-05-21T03:34:23
Computati+ alan-compute-07     FAILED   00:02:04 2019-05-21T03:35:06
Computati+ alan-compute-07     FAILED   00:01:48 2019-05-21T03:35:28
Computati+ alan-compute-07     FAILED   00:01:50 2019-05-21T03:36:16
Computati+ alan-compute-07     FAILED   00:01:49 2019-05-21T03:37:10
Computati+ alan-compute-07     FAILED   00:02:02 2019-05-21T03:37:16
Computati+ alan-compute-07     FAILED   00:01:56 2019-05-21T03:38:06
Computati+ alan-compute-07     FAILED   00:02:04 2019-05-21T03:38:59
Computati+ alan-compute-07     FAILED   00:01:55 2019-05-21T03:39:18
Computati+ alan-compute-07     FAILED   00:01:36 2019-05-21T13:49:00
Computati+ alan-compute-07     FAILED   00:01:34 2019-05-21T13:50:36
Computati+ alan-compute-07     FAILED   00:01:34 2019-05-21T13:52:10
Computati+ alan-compute-07     FAILED   00:01:35 2019-05-21T14:00:37
Computati+ alan-compute-07     FAILED   00:01:35 2019-05-21T14:02:12
Computati+ alan-compute-07     FAILED   00:01:33 2019-05-21T14:03:47
Computati+ alan-compute-07     FAILED   00:01:33 2019-05-21T14:05:20
Computati+ alan-compute-07     FAILED   00:01:36 2019-05-21T14:21:15
Computati+ alan-compute-07     FAILED   00:01:32 2019-05-21T14:24:51
Computati+ alan-compute-07     FAILED   00:01:35 2019-05-21T14:26:23
Computati+ alan-compute-07     FAILED   00:01:38 2019-05-21T14:27:58
Computati+ alan-compute-07     FAILED   00:01:40 2019-05-21T14:28:42
Computati+ alan-compute-07     FAILED   00:01:34 2019-05-21T14:29:36
Computati+ alan-compute-07     FAILED   00:01:45 2019-05-21T14:30:22
Computati+ alan-compute-07     FAILED   00:01:41 2019-05-21T14:31:10
Computati+ alan-compute-07     FAILED   00:01:39 2019-05-21T14:32:07
Computati+ alan-compute-07     FAILED   00:01:46 2019-05-21T14:32:51
```

```
$ sacct -u rmormont --format="JobName,Nodelist,State,Elapsed,Start" | grep "alan-compute-0\(1\|2\|3\|4\|5\|6\)"
[...]
Computati+ alan-compute-01    TIMEOUT   00:25:28 2019-05-21T03:13:17
Computati+ alan-compute-05  COMPLETED   00:07:19 2019-05-21T03:13:47
Computati+ alan-compute-05  COMPLETED   00:06:59 2019-05-21T03:13:47
Computati+ alan-compute-03  COMPLETED   00:06:18 2019-05-21T03:14:28
Computati+ alan-compute-01  COMPLETED   00:12:52 2019-05-21T03:14:38
Computati+ alan-compute-05  COMPLETED   00:13:08 2019-05-21T03:20:46
Computati+ alan-compute-03  COMPLETED   00:12:07 2019-05-21T03:20:46
Computati+ alan-compute-05  COMPLETED   00:13:18 2019-05-21T03:21:07
Computati+ alan-compute-02  COMPLETED   00:09:56 2019-05-21T03:23:24
Computati+ alan-compute-02  COMPLETED   00:16:37 2019-05-21T03:26:32
Computati+ alan-compute-01  COMPLETED   00:07:45 2019-05-21T03:27:30
Computati+ alan-compute-05  COMPLETED   00:07:30 2019-05-21T03:28:19
Computati+ alan-compute-03  COMPLETED   00:06:44 2019-05-21T03:32:53
Computati+ alan-compute-02  COMPLETED   00:11:11 2019-05-21T03:33:20
Computati+ alan-compute-05  COMPLETED   00:13:36 2019-05-21T03:33:54
Computati+ alan-compute-05  COMPLETED   00:13:42 2019-05-21T03:34:25
Computati+ alan-compute-01  COMPLETED   00:13:37 2019-05-21T03:35:15
Computati+ alan-compute-05  COMPLETED   00:07:27 2019-05-21T03:35:49
Computati+ alan-compute-03  COMPLETED   00:06:39 2019-05-21T03:35:58
Computati+ alan-compute-01  COMPLETED   00:13:16 2019-05-21T03:38:49
Computati+ alan-compute-03  CANCELLED   00:02:03 2019-05-21T13:41:15
Computati+ alan-compute-03  CANCELLED   00:02:03 2019-05-21T13:41:15
Computati+ alan-compute-03  COMPLETED   00:14:24 2019-05-21T13:49:00
Computati+ alan-compute-03  COMPLETED   00:20:03 2019-05-21T13:49:00
Computati+ alan-compute-03  COMPLETED   00:14:03 2019-05-21T14:03:24
Computati+ alan-compute-04  COMPLETED   00:20:13 2019-05-21T14:21:15
Computati+ alan-compute-03  COMPLETED   00:15:08 2019-05-21T14:21:15
Computati+ alan-compute-03  COMPLETED   00:20:50 2019-05-21T14:21:15
Computati+ alan-compute-03  COMPLETED   00:20:12 2019-05-21T14:21:15
Computati+ alan-compute-01  COMPLETED   00:14:48 2019-05-21T14:26:20
```

**Comment by JoeriHermans** [comment]
Other jobs seem to be running just fine. There are issues on compute-06 though, I'm draining the node to do a restart.

**Comment by JoeriHermans** [comment]
@waliens Related: https://discuss.pytorch.org/t/solved-rtx-2080-ti-cudnn-error-occurs-when-loading-rnn-model-to-gpu/33880

Solution: Update CUDA / install new PyTorch version.

**Comment by waliens** [comment]
Problem solved thanks !
